export const books =[
    {
        id: 1,
        title: "The Pragmatic Programmer",
        author: "Andrew Hunt and David Thomas",
        year: 1999,
        genre: "Software Development",
    },
    {
        id: 2,
        title: "Clean Code: A Handbook of Agile Software Craftsmanship",
        author: "Robert C. Martin",
        year: 2008,
        genre: "Software Development",
    },
    {
        id: 3,
        title: "Design Patterns: Elements of Reusable Object-Oriented Software",
        author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
        year: 1994,
        genre: "Software Development",
    },
    {
        id: 4,
        title: "The Lean Startup: How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses",
        author: "Eric Ries",
        year: 2011,
        genre: "Business",
    },
    {
        id: 5,
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        year: 2011,
        genre: "Psychology",
    },
    {
        id: 6,
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        year: 2011,
        genre: "History",
    },
    {
        id: 7,
        title: "The Art of War",
        author: "Sun Tzu",
        year: "5th century BC",
        genre: "Military Strategy",
    },
    {
        id: 8,
        title: "The Hitchhiker's Guide to the Galaxy",
        author: "Douglas Adams",
        year: 1979,
        genre: "Science Fiction",
    },
    {
        id: 9,
        title: "1984",
        author: "George Orwell",
        year: 1949,
        genre: "Dystopian Fiction",
    },
    {
        id: 10,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        year: 1960,
        genre: "Classic Literature",
    },
]